version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
    ports:
      - "9090:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - ktb-community-overlay
    volumes:
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - ktb-community-overlay
    volumes:
      - grafana_data:/var/lib/grafana

configs:
  prometheus_config:
    file: ./prometheus.yml

networks:
  ktb-community-overlay:
    external: true

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local